version: "3.9"
services:
  db:
    image: mysql:8.0
    env_file: .env
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 15

  app:
    build: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  tests:
    build: .
    command: mvn verify
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
