services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1",
             "-u", "${MYSQLDB_USER}", "-p${MYSQLDB_PASSWORD}"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build: .
    restart: on-failure
    depends_on:
      mysqldb:
        condition: service_healthy
    env_file: ./.env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_APPLICATION_JSON: >
        {
          "spring":{
            "datasource":{
              "url":"jdbc:mysql://mysqldb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC",
              "username":"${MYSQLDB_USER}",
              "password":"${MYSQLDB_PASSWORD}"
            },
            "jpa":{
              "database-platform":"org.hibernate.dialect.MySQLDialect",
              "hibernate":{"ddl-auto":"update"},
              "show-sql": true,
              "open-in-view": false
            },
            "thymeleaf":{"cache":false}
          },
          "server":{"port":"${SPRING_DOCKER_PORT}"}
        }
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    volumes:
      - mvn_repo:/root/.m2   

volumes:
  db:
  mvn_repo:
